#zf190225.1349

version: '3'

services:
  # Version with built-in static configuration
  # prom:
  #   build: prom
  #   ports: 
  #     - "9090:9090"
  #   volumes:
  #     - promdata:/prometheus

  # Standard version with config in host filesystem
  prom:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    restart: always
    volumes:
      - promdata:/prometheus
      - ./prom/prometheus.conf:/etc/prometheus/prometheus.yml

  pgateway:
    image: prom/pushgateway
    ports: 
      - "9091:9091"
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "9092:3000"
    restart: always
    volumes:
      - grafdata:/var/lib/grafana
    # environment:
    #   GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    #   GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/admin_password
    # secrets:
    #   - admin_password

volumes:
  promdata:
    driver: local
  grafdata:
    driver: local

# secrets:
#   admin_password:
#     file: ./secrets/admin_password.txt

#   dataexample:
#     image: 
